# Generated by Django 4.0.4 on 2022-06-15 01:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0002_alter_task_done'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='done',
            field=models.CharField(choices=[('doing', 'Aberto'), ('done', 'Fechado')], max_length=5),
        ),
    ]
