# Generated by Django 4.0.4 on 2022-06-28 02:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0005_alter_task_done'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='adress',
            field=models.TextField(default='teste'),
            preserve_default=False,
        ),
    ]
