# Generated by Django 4.0.4 on 2022-06-28 02:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0006_task_adress'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='adress',
            field=models.CharField(max_length=255),
        ),
    ]
